/* -------------------------------------------------------------------------- */
/* The classics the feed never shows                                          */
/* -------------------------------------------------------------------------- */

/*
 * BonusHunt's feed only lists games added in the last week, so the catalog
 * never learned the slots chat asks for most — Gates of Olympus, Sugar Rush,
 * The Dog House, Big Bass Bonanza. These are added once, by hand, as 'manual'
 * rows.
 *
 * The key is built exactly as `keyFor` builds it in lib/store/slots.ts
 * (lowercase letters and digits of the name, a bar, the same of the
 * provider), and the providers are spelled the way the feed spells them, so
 * a later sync that does list one of these merges into this row instead of
 * adding a second. Anything already in the catalog is left alone.
 *
 * No art: there is no source for it that we are allowed to copy, and the
 * pages fall back to the slot's initials. Art can be added per slot on
 * /admin/slots.
 */
INSERT INTO slots (key, name, provider, source)
SELECT regexp_replace(lower(name), '[^a-z0-9]', '', 'g') || '|' ||
       regexp_replace(lower(provider), '[^a-z0-9]', '', 'g'),
       name, provider, 'manual'
  FROM (VALUES
    -- Pragmatic Play
    ('Gates of Olympus', 'Pragmatic Play'),
    ('Gates of Olympus 1000', 'Pragmatic Play'),
    ('Sweet Bonanza', 'Pragmatic Play'),
    ('Sweet Bonanza 1000', 'Pragmatic Play'),
    ('Sugar Rush', 'Pragmatic Play'),
    ('Sugar Rush 1000', 'Pragmatic Play'),
    ('Starlight Princess', 'Pragmatic Play'),
    ('Starlight Princess 1000', 'Pragmatic Play'),
    ('The Dog House', 'Pragmatic Play'),
    ('The Dog House Megaways', 'Pragmatic Play'),
    ('The Dog House Multihold', 'Pragmatic Play'),
    ('Big Bass Bonanza', 'Pragmatic Play'),
    ('Bigger Bass Bonanza', 'Pragmatic Play'),
    ('Big Bass Splash', 'Pragmatic Play'),
    ('Fruit Party', 'Pragmatic Play'),
    ('Fruit Party 2', 'Pragmatic Play'),
    ('Wild West Gold', 'Pragmatic Play'),
    ('Wild West Gold Megaways', 'Pragmatic Play'),
    ('Madame Destiny Megaways', 'Pragmatic Play'),
    ('Great Rhino Megaways', 'Pragmatic Play'),
    ('Wolf Gold', 'Pragmatic Play'),
    ('Buffalo King Megaways', 'Pragmatic Play'),
    ('Gems Bonanza', 'Pragmatic Play'),
    ('Zeus vs Hades - Gods of War', 'Pragmatic Play'),
    ('Power of Thor Megaways', 'Pragmatic Play'),
    ('Floating Dragon', 'Pragmatic Play'),
    ('Curse of the Werewolf Megaways', 'Pragmatic Play'),
    ('Release the Kraken', 'Pragmatic Play'),
    ('Chilli Heat', 'Pragmatic Play'),
    ('5 Lions Megaways', 'Pragmatic Play'),
    ('Joker''s Jewels', 'Pragmatic Play'),
    ('Mustang Gold', 'Pragmatic Play'),
    ('Muertos Multiplier Megaways', 'Pragmatic Play'),
    ('Cleocatra', 'Pragmatic Play'),
    ('Candy Blitz', 'Pragmatic Play'),
    ('Fire Portals', 'Pragmatic Play'),
    ('Twilight Princess', 'Pragmatic Play'),
    ('Book of the Fallen', 'Pragmatic Play'),
    ('Sweet Powernudge', 'Pragmatic Play'),
    ('Heist for the Golden Nuggets', 'Pragmatic Play'),
    -- Hacksaw Gaming
    ('Wanted Dead or a Wild', 'Hacksaw Gaming'),
    ('Chaos Crew', 'Hacksaw Gaming'),
    ('Chaos Crew II', 'Hacksaw Gaming'),
    ('Le Bandit', 'Hacksaw Gaming'),
    ('Le Pharaoh', 'Hacksaw Gaming'),
    ('Le Viking', 'Hacksaw Gaming'),
    ('Le King', 'Hacksaw Gaming'),
    ('Hand of Anubis', 'Hacksaw Gaming'),
    ('Dork Unit', 'Hacksaw Gaming'),
    ('RIP City', 'Hacksaw Gaming'),
    ('Stack''em', 'Hacksaw Gaming'),
    ('Beam Boys', 'Hacksaw Gaming'),
    ('Densho', 'Hacksaw Gaming'),
    ('Stick''em', 'Hacksaw Gaming'),
    ('Itero', 'Hacksaw Gaming'),
    ('Gladiator Legends', 'Hacksaw Gaming'),
    ('Rotten', 'Hacksaw Gaming'),
    ('Frutz', 'Hacksaw Gaming'),
    ('Joker Bombs', 'Hacksaw Gaming'),
    ('Cubes 2', 'Hacksaw Gaming'),
    ('Miami Multiplier', 'Hacksaw Gaming'),
    ('Toshi Video Club', 'Hacksaw Gaming'),
    ('Duel at Dawn', 'Hacksaw Gaming'),
    ('Twisted Lab', 'Hacksaw Gaming'),
    ('Xpander', 'Hacksaw Gaming'),
    ('Pray For Three', 'Hacksaw Gaming'),
    ('Rad Maxx', 'Hacksaw Gaming'),
    ('Klowns', 'Hacksaw Gaming'),
    ('Magic Piggy', 'Hacksaw Gaming'),
    ('Cash Crew', 'Hacksaw Gaming'),
    ('Om Nom', 'Hacksaw Gaming'),
    ('Keep''em', 'Hacksaw Gaming'),
    -- Nolimit City
    ('Mental', 'Nolimit City'),
    ('Mental 2', 'Nolimit City'),
    ('San Quentin xWays', 'Nolimit City'),
    ('San Quentin 2: Death Row', 'Nolimit City'),
    ('Tombstone', 'Nolimit City'),
    ('Tombstone RIP', 'Nolimit City'),
    ('Tombstone Slaughter', 'Nolimit City'),
    ('Fire in the Hole xBomb', 'Nolimit City'),
    ('Fire in the Hole 2', 'Nolimit City'),
    ('Fire in the Hole 3', 'Nolimit City'),
    ('Deadwood', 'Nolimit City'),
    ('Deadwood R.I.P', 'Nolimit City'),
    ('Punk Rocker', 'Nolimit City'),
    ('Punk Toilet', 'Nolimit City'),
    ('Folsom Prison', 'Nolimit City'),
    ('East Coast vs West Coast', 'Nolimit City'),
    ('Das xBoot', 'Nolimit City'),
    ('xWays Hoarder xSplit', 'Nolimit City'),
    ('Misery Mining', 'Nolimit City'),
    ('Book of Shadows', 'Nolimit City'),
    ('Karen Maneater', 'Nolimit City'),
    ('Serial', 'Nolimit City'),
    ('Remember Gulag', 'Nolimit City'),
    ('Kiss My Chainsaw', 'Nolimit City'),
    ('Blood & Shadow', 'Nolimit City'),
    ('Bushido Ways xNudge', 'Nolimit City'),
    ('Infectious 5 xWays', 'Nolimit City'),
    ('Poison Eve', 'Nolimit City'),
    ('El Paso Gunfight xNudge', 'Nolimit City'),
    ('Barbarian Fury', 'Nolimit City'),
    ('Pixies vs Pirates', 'Nolimit City'),
    ('Dungeon Quest', 'Nolimit City'),
    ('Warrior Graveyard xNudge', 'Nolimit City'),
    ('Evil Goblins xBomb', 'Nolimit City'),
    ('Gluttony', 'Nolimit City'),
    ('Duck Hunters', 'Nolimit City'),
    ('Hot Nudge', 'Nolimit City'),
    ('Tractor Beam', 'Nolimit City'),
    ('The Crypt', 'Nolimit City'),
    ('Nine to Five', 'Nolimit City'),
    ('Outsourced', 'Nolimit City'),
    ('Stockholm Syndrome', 'Nolimit City'),
    ('Beheaded', 'Nolimit City'),
    ('Disturbed', 'Nolimit City'),
    ('Rock Bottom', 'Nolimit City'),
    -- Relax Gaming
    ('Money Train 2', 'Relax Gaming'),
    ('Money Train 3', 'Relax Gaming'),
    ('Money Train 4', 'Relax Gaming'),
    ('Temple Tumble Megaways', 'Relax Gaming'),
    ('Iron Bank', 'Relax Gaming'),
    ('Dead Man''s Trail', 'Relax Gaming'),
    ('Hellcatraz', 'Relax Gaming'),
    ('Snake Arena', 'Relax Gaming'),
    ('Book of 99', 'Relax Gaming'),
    -- Push Gaming
    ('Jammin'' Jars', 'Push Gaming'),
    ('Jammin'' Jars 2', 'Push Gaming'),
    ('Razor Shark', 'Push Gaming'),
    ('Razor Returns', 'Push Gaming'),
    ('Fat Rabbit', 'Push Gaming'),
    ('Fat Banker', 'Push Gaming'),
    ('Wild Swarm', 'Push Gaming'),
    ('Retro Tapes', 'Push Gaming'),
    ('Mount Magmas', 'Push Gaming'),
    ('Big Bamboo', 'Push Gaming'),
    ('Fire Hopper', 'Push Gaming'),
    ('Tiki Tumble', 'Push Gaming'),
    ('Dinopolis', 'Push Gaming'),
    -- Big Time Gaming
    ('Bonanza', 'Big Time Gaming'),
    ('Extra Chilli', 'Big Time Gaming'),
    ('White Rabbit', 'Big Time Gaming'),
    ('Danger High Voltage', 'Big Time Gaming'),
    ('Who Wants to Be a Millionaire', 'Big Time Gaming'),
    ('Lil Devil', 'Big Time Gaming'),
    -- Play'n Go
    ('Book of Dead', 'Play''n Go'),
    ('Legacy of Dead', 'Play''n Go'),
    ('Rise of Olympus', 'Play''n Go'),
    ('Rise of Olympus 100', 'Play''n Go'),
    ('Reactoonz', 'Play''n Go'),
    ('Reactoonz 2', 'Play''n Go'),
    ('Moon Princess', 'Play''n Go'),
    ('Fire Joker', 'Play''n Go'),
    ('Gemix', 'Play''n Go'),
    ('Rich Wilde and the Tome of Madness', 'Play''n Go'),
    -- NetEnt
    ('Starburst', 'NetEnt'),
    ('Gonzo''s Quest', 'NetEnt'),
    ('Dead or Alive', 'NetEnt'),
    ('Dead or Alive 2', 'NetEnt'),
    ('Twin Spin', 'NetEnt'),
    ('Divine Fortune', 'NetEnt'),
    ('Blood Suckers', 'NetEnt'),
    ('Mega Fortune', 'NetEnt'),
    -- ELK Studios
    ('Cygnus', 'ELK Studios'),
    ('Cygnus 2', 'ELK Studios'),
    ('Wild Toro', 'ELK Studios'),
    ('Wild Toro 2', 'ELK Studios'),
    ('Pirots', 'ELK Studios'),
    ('Pirots 2', 'ELK Studios'),
    ('Pirots 3', 'ELK Studios'),
    ('Ecuador Gold', 'ELK Studios'),
    ('Katmandu Gold', 'ELK Studios'),
    -- Red Tiger Gaming
    ('Gonzo''s Quest Megaways', 'Red Tiger Gaming'),
    ('Piggy Riches Megaways', 'Red Tiger Gaming'),
    ('Pirates'' Plenty', 'Red Tiger Gaming'),
    -- Thunderkick
    ('Esqueleto Explosivo', 'Thunderkick'),
    ('Esqueleto Explosivo 2', 'Thunderkick'),
    ('Midas Golden Touch', 'Thunderkick'),
    ('Pink Elephants', 'Thunderkick'),
    ('Pink Elephants 2', 'Thunderkick'),
    -- Yggdrasil
    ('Vikings Go Berzerk', 'Yggdrasil'),
    ('Valley of the Gods', 'Yggdrasil'),
    ('Raptor DoubleMax', 'Yggdrasil'),
    -- Quickspin
    ('Big Bad Wolf', 'Quickspin'),
    ('Sakura Fortune', 'Quickspin'),
    -- PG Soft
    ('Mahjong Ways', 'PG Soft'),
    ('Mahjong Ways 2', 'PG Soft'),
    ('Fortune Tiger', 'PG Soft'),
    ('Fortune Ox', 'PG Soft'),
    ('Fortune Rabbit', 'PG Soft'),
    ('Lucky Neko', 'PG Soft'),
    ('Treasures of Aztec', 'PG Soft'),
    -- BGaming
    ('Elvis Frog in Vegas', 'BGaming')
  ) AS classics(name, provider)
ON CONFLICT (key) DO NOTHING;
